name: GitHub Actions Maven Build Example

on:
  push:
    branches: [master]

jobs:
  build-on-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Step1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 15
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: Step3 - Build Maven Project
        run: mvn --batch-mode -DskipTests package

      - name: Step4 - Run test cases
        run: mvn -e -X --batch-mode -Dmaven.test.failure.ignore=true test
